# This is a basic workflow to help you get started with Actions

name: generate_reference

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create Documentation Directory
        run: mkdir -p ${{ github.workspace }}/docs

      - name: Generate Documentation
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/game \
            -v ${{ github.workspace }}/docs:/output \
            gdquest/gdscript-docs-maker:latest \
            /game -o /output

      - name: Commit documentation
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add docs/
          git commit -m "Update documentation 📚"
          git push
